export enum Prefecture {
  HOKKAIDO = "hokkaido",
  AOMORI = "aomori",
  IWATE = "iwate",
  MIYAGI = "miyagi",
  AKITA = "akita",
  YAMAGATA = "yamagata",
  FUKUSHIMA = "fukushima",
  IBARAKI = "ibaraki",
  TOCHIGI = "tochigi",
  GUNMA = "gunma",
  SAITAMA = "saitama",
  CHIBA = "chiba",
  TOKYO = "tokyo",
  KANAGAWA = "kanagawa",
  NIIGATA = "niigata",
  TOYAMA = "toyama",
  ISHIKAWA = "ishikawa",
  FUKUI = "fukui",
  YAMANASHI = "yamanashi",
  NAGANO = "nagano",
  GIFU = "gifu",
  SHIZUOKA = "shizuoka",
  AICHI = "aichi",
  MIE = "mie",
  SHIGA = "shiga",
  KYOTO = "kyoto",
  OSAKA = "osaka",
  HYOGO = "hyogo",
  NARA = "nara",
  WAKAYAMA = "wakayama",
  TOTTORI = "tottori",
  SHIMANE = "shimane",
  OKAYAMA = "okayama",
  HIROSHIMA = "hiroshima",
  YAMAGUCHI = "yamaguchi",
  TOKUSHIMA = "tokushima",
  KAGAWA = "kagawa",
  EHIME = "ehime",
  KOCHI = "kochi",
  FUKUOKA = "fukuoka",
  SAGA = "saga",
  NAGASAKI = "nagasaki",
  KUMAMOTO = "kumamoto",
  OITA = "oita",
  MIYAZAKI = "miyazaki",
  KAGOSHIMA = "kagoshima",
  OKINAWA = "okinawa",
}

export const getPrefectureOptions = (t: (key: string) => string) => {
  return Object.values(Prefecture).map(value => ({
    value,
    label: t(`prefectures.${value}`)
  }));
};
